site_name: Innovation Options
theme:
  name: material
markdown_extensions:
  - footnotes
  - meta
  - tables
plugins:
  - search
extra:
  generator: false
nav:
  - Home: index.md
  - Posts:
    # - The Accounting IS the Problem: accounting-is-the-problem.md
    - Calculate Option: posts/calculate_option/index.md
    - Calculate Option: posts/calculate_option/index.md
    - Calculate Option: posts/calculate_option/index.md
    - Calculate Option: posts/calculate_option/index.md
