site_name: Innovation Options
theme:
  name: material
markdown_extensions:
  - footnotes
  - meta
  - tables
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
extra:
  generator: false
docs_dir: 'content'
nav:
  - Home: index.md
  - Learn: learn.md
  - Calculator: calculator.md
  - Posts:
    - posts/measuring-learning/index.md
    - posts/option_mindset/index.md
    - posts/options_explained/index.md
    - posts/calculate_option/index.md
    - posts/wom_prom_score/index.md
    - posts/diffusion_of_innovations/index.md
    - posts/innovation_engine/index.md
    - posts/quest_race_grind/index.md
    - posts/three_innovation_types/index.md
    # - posts/innovation_metrics/index.md
    # - posts/laddered_innovation/index.md
    # - posts/npv_trap/index.md
    # - posts/options_characteristics/index.md
    # - posts/accounting_problem/index.md
    # - posts/angels_and_options/index.md
extra_javascript:
  - javascript/mathjax.js
  - javascript/calculator.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - styles/calculator.css
