site_name: Innovation Options
theme:
  name: material
markdown_extensions:
  - footnotes
  - meta
  - tables
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
extra:
  generator: false
nav:
  - Home: index.md
  - Posts:
    # - The Accounting IS the Problem: accounting-is-the-problem.md
    - posts/measuring_learning/index.md
    - posts/calculate_option/index.md
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
